### ISSUE TITLE
一些中国的ddlc粉丝的建议/Advice from some Chinese ddlc fans 

### ISSUE THREAD

**Issue by mtr-static-official** [DokiDokiModManager/Mod-Manager#191]
“Doki Doki Mod Manager”的作者您好，这里是中国的一位ddlc粉丝。您的“Doki Doki Mod
Manager”在中国境内有以下问题（至于为什么我会在第二条解释）
Hello, author of "Doki Doki Mod Manager", here is a ddlc fan in China.
You have the following problem with "Doki Doki Mod Manager" in China
As to why I explained in the second article).

我将使用中文与英文与您对话，英文翻译来自deepl.com。
I will talk to you in both Chinese and English, with English translation from deepl.com.

1.网站为英文。中国 并未普及英语，而机器翻译的效果一般不尽人意，很多人甚至根本无法理解机器翻译。
The site is in English. English is not widely spoken in China, and machine translation is generally unsatisfactory, and many people do not even understand it.

2.GitHub在中国遭遇限速! 没错!
在中国，我们不能用谷歌搜索，不能发推特，不能在维基百科上查资料，甚至GitHub也受到了中国GreatCannon的攻击！在中国，我们下载GitHub档案的速度不超过100kb，这是事实。（这个是因为GitHub的上游服务商aws的问题）
GitHub suffers speed limit in China! That's right! In China, we can't use Google to search, we can't tweet, we can't look up information on Wikipedia, and even GitHub has been attacked by China's GreatCannon!The speed at which we download GitHub archives in China is no more than 100kb. that's a fact.(This is because of issues with GitHub's upstream service provider aws)

3.Doki Doki Mod Club在中国更是缓慢！没错！中国的网络环境极其恶劣。就是这样。
Doki Doki Mod Club is even slower in China! That's right! China's cyber environment is extremely hostile. That's it.

4.几乎没有的中文mod！您知道的，中文mod大多数是本地化而来，但是只有寥寥几个是官方认可的翻译（尽管翻译得到了官方授权），且目前中国还没有一个mod收集的平台，mod都是翻译者在贴吧论坛之类的地方发布！
As you know, most of the Chinese mods are localized, but only a few are officially translated (even though the translations are officially authorized), and there is no mod-collecting platform in China yet, mods are just posted by translators on forums and the like!

我真的很爱这个游戏和圈子，而我则乐意改进Doki Doki Mod Manager。针对以上四条，我有以下建议：
I really love the game and the circle, while I am happy to improve Doki Doki Mod Manager.In response to the four items above, I have the following suggestions.

1.我可以提供网站的中文翻译。
1. I can provide Chinese translation of the website.

2.我可以提供您的所有关于Doki Doki Mod Manager的镜像存储。
2.I can provide you with mirror storage for all of your Doki Doki Mod Manager.

3.对于网站缓慢我无能为力。
I can't do anything about the slow site.

4.我有绝佳的办法！我可以搭建doki doki chinese mod网站，并且我请求您将我的网站纳入Doki Doki Mod Manager的mod存储！
I have the perfect solution! I can build a doki doki chinese mod site and I ask that you include my site in the mod store of Doki Doki Mod Manager!

以上是鄙人的少许拙见，希望可以采纳。
This is my humble opinion and I hope it can be adopted.

一个来自中国的ddlc粉丝，MTR。
A ddlc fan from China, mtr.

**Comment by Niquolas** [comment]
Thank you, I have replied to your email.
谢谢你，我已经回复了你的邮件。
