### ISSUE TITLE
Can't Close

### ISSUE THREAD

**Issue by zombiepigdragon** [DokiDokiModManager/Mod-Manager#66]
On my fairly standard Kubuntu install, it's impossible to close the Mod Manager via the GUI. The close button doesn't work, the right-click menu doesn't work, the "sorry but I crashed" menu doesn't work. These are simply ignored.

**Comment by ZudoMC** [comment]
I've been unable to reproduce this issue on Linux Mint. I'll try with
Kubuntu when I get the opportunity.

Could you tell me exactly which version you are using, and what you were
doing when you noticed the issue?

**Comment by zombiepigdragon** [comment]
This seems to only happen when I first started it up, it works fine now. I think it's either the fact I hadn't given it a copy of DDLC yet or the fact I had system borders disabled.

**Comment by zombiepigdragon** [comment]
I'm going to close this; my install was pretty borked at the time, this just happened to be one of its first symptoms.
