### ISSUE TITLE
macOS Icon is missing

### ISSUE THREAD

**Issue by alicerunsonfedora** [DokiDokiModManager/Mod-Manager#71]
The icon for Doki Doki Mod Manager on macOS is missing. I'm not sure if this is an Electron misconfiguration, but it's worth looking into. This occurs on the latest version of the app.

<img width="154" alt="image" src="https://user-images.githubusercontent.com/13445064/58769467-6a252d80-8575-11e9-919e-161c14dc5747.png">

Currently running macOS Mojave (10.14.5) on a MacBook Pro 2017 (base model).

**Comment by ZudoMC** [comment]
I'll look into this, although it's slightly tricky as I don't have a mac to test on.

**Comment by alicerunsonfedora** [comment]
I took a look at the project, and it looks like it's just an issue with the icon file. Says it's not valid.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/13445064/58967789-d32dc080-8782-11e9-888e-ea6b11ee701a.png">

I'll make a PR to fix this real quick for ya.
